// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljgwvmypghdsuvhqgxcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqZ3d2bXlwZ2hkc3V2aHFneGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMTk1NzUsImV4cCI6MjA3ODU5NTU3NX0.kkZq1rhZ52NKXrXFGMtsTShbpvV7geaDP249weas7ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});